[general]
import = [
	"~/.config/alacritty/themes/themes/google.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
decorations = "Buttonless"
title = "Alacritty"
option_as_alt = "Both"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window.class]
general = "Alacritty"
instance = "Alacritty"
