[general]
import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
decorations = "Buttonless"
title = "Alacritty"
option_as_alt = "Both"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window.class]
general = "Alacritty"
instance = "Alacritty"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
